### ISSUE TITLE
Possible typo?

### ISSUE THREAD

**Issue by hineios** [DST-Tools/DSTEd-Languages#2]
I've been working on a translation into PT-PT, but I've found something rather curious that I believe to be a typo.

On line 89 of the xx_XX.json file you have the following:
`"Rember...": "Rember...",`

I believe its a typo for remember?
(I've meddled in the app but can't seem to find where is this used...)

Also I would like to suggest that you keep the same nomenclature as Steam for the number of favourites ans subscriptions on mods.
Steam uses the term "Unique" where you use "Lifetime", it may be a little bit confusing (It was for me).

**Comment by Bizarrus** [comment]
Okay, the Typo is correct, it means `Remember`.

You can find these, if you modify a File and want to close the Software completely (See https://github.com/DST-Tools/DSTEd/blob/29719ea044234c22cd9561c2b24b1d8bf534c2b7/Source/Window/IDE.js#L372):

- If you click "Don\'t Save", the recent files will be not changed:
- Save the changes before closing?
- Rember...

These Screen was implemented in few minutes and is not complete:
![Save](https://abload.de/img/saveshp7u.png)

**Comment by hineios** [comment]
OK, didn't know that was a thing 👍
